:loop
	:: change encoding of html websites generated by OE
	
	:: one stage event (remove the :: from the begininng of the lines you want to use)
	iconv -f windows-1250 -t utf-8 weresult.html > result.html
	iconv -f windows-1250 -t utf-8 wesplitresult.html > splitresult.html
	
	:: two-stage event (remove the :: from the begininng of the lines you want to use)
	:: iconv -f windows-1250 -t utf-8 weresult1.html > result1.html
	:: iconv -f windows-1250 -t utf-8 wesplitresult1.html > splitresult1.html
	:: iconv -f windows-1250 -t utf-8 weresult2.html > result2.html
	:: iconv -f windows-1250 -t utf-8 wesplitresult2.html > splitresult2.html
	:: iconv -f windows-1250 -t utf-8 wetotalresults.html > totalresult.html


	:: Navigate to the directory you wish to push to GitHub
	::Change <path> as needed. Eg. C:\Users\rich\Desktop\Writings
	::cd <path>

	::Initialize GitHub
	git init

	::Pull any external changes (maybe you deleted a file from your repo?)
	git pull

	::Add all files in the directory
	git add --all

	::Commit all changes with the message "auto push".
	::Change as needed.
	git commit -m "auto push"

	::Push all changes to GitHub
	git push

	::Alert user to script completion and relaunch.
	echo Complete. Relaunching...

	::Wait 120 seconds until going to the start of the loop.
	::Change as needed.
	TIMEOUT 120

::Restart from the top.
goto loop
